#Numpy
리스트와 유사하지만 배열이 크기가 커져도 높은 성능을 보장하며, 다양한 수학 관련 함수 내장.
리스트와 달리, 동일한 자료형만 담을 수 있음.

#ndarray 객체 생성
array(): 리스트, 튜플 등 데이터를 이용해 ndarray 객체생성
random.randn(): 정규분포 난수생성
zeros(): 객체 생성 후 0으로 초기화
ones(): 객체 생성 후 1로 초기화
arange(): 내장함수 range()와 동일한 기능
reshape(): 차원을 재구성
transpose(): 행렬의 전치
flatten(): 다차원 배열을 1차원 배열로 평탄화
sqeez(): 비어있는 차원 제거

#ndarray 객체 사용
sum(): 합계 반환 
mean(): 평균값 반환
max(): 최대값 반환
min(): 최소값 반환
std(): 표준편차
var(): 분산
argmax(): 최대값을 가지는 요소의 인덱스 반환
argmin(): 최소값을 가지는 요소의 인덱스 반환
where(): 조건식에 따라 배열의 요소 값을 특정 값으로 변경
sort(): 배열을 오름차순으로 정렬

trace(A): 행렬 A의 대각합 (Trace) 계산
linalg.cholesky(A): 행렬 A의 Cholesky 분해
linalg.qr(A): 행렬 A의 QR 분해
linalg.svd(A): 행렬 A의 특이값 분해 (SVD)

#행렬연산
add(A, B): 두 행렬 A와 B의 요소별 덧셈
subtract(A, B): 두 행렬 A와 B의 요소별 뺄셈
multiply(A, B): 두 행렬 A와 B의 요소별 곱셈
divide(A, B): 두 행렬 A와 B의 요소별 나눗셈
dot(A, B): 두 행렬의 행렬 곱셈
matmul(A, B): 행렬 곱셈 (배치 행렬 곱셈 포함)
linalg.inv(A): 행렬 A의 역행렬
linalg.det(A): 행렬 A의 행렬식 계산
linalg.eig(A): 행렬 A의 고유값과 고유벡터 계산
linalg.norm(A): 행렬 A의 노름 계산
linalg.solve(A, B): 선형 연립 방정식 Ax = B를 푸는 해 x 계산




In [3]:
import numpy as np
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([[1,2,3],[4,5,6]])
print(ar1)
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
ar3 = np.random.randn(3) #3 크기의 1차원 배열 생성
ar4 = np.random.randn(2,3) #2*3 크기의 2차원 배열을 생성
print(ar3)
print(ar4)


[ 0.50935645  1.58570421 -0.41927664]
[[-0.03817219 -0.46463433 -0.5506665 ]
 [ 0.12971586  0.36676354 -0.36409864]]


In [5]:
ar5 = np.zeros(5)
ar6 = np.ones((2,3))
print(ar5)
print(ar6)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
ar7 = np.arange(20,200,10)
ar8 = ar7.reshape(3,6)
print(ar7)
print(ar8)

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]


In [13]:
#ndarray의 인덱싱
ar1 = np.arange(1,21,1)
print(ar1)
print(ar1[1])

ar2 =ar1.reshape(2,10)
print(ar2)
ar2[1][1] = 100
print(ar2[1][0:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[ 11 100  13]


In [14]:
ar1 = np.arange(1,11,1)
ar2 = ar1 + 3 #broadcasting
ar3 = ar1 * 2
print(ar1)
print(ar2, "\n", ar3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


In [18]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.std())
print(ar1.var())
print(ar1.max())
print(ar1.min())
print(ar1.max(axis=0)) #열 방향(결과는 행)
print(ar1.max(axis=1)) #행 방향 max(결과는 열)

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
7.651353466971919
58.5432098765432
19
-7
[ 6  9 19]
[ 9 19 11]


In [24]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1>0) #각 원소가 0보다 큰지 판단한 결과(T/F행렬)
m_count = (ar1<0).sum() #원소 중 음수가 몇개인지 계산
print(m_count)

ar2 = np.where(ar1<0,0,ar1) #0보다 작은 원소를 0으로 변경
print(ar2)

[[ True  True  True]
 [False False  True]
 [ True  True  True]]
2
[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]


In [28]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
ar1.sort(0) #열 단위로 원소를 정렬
print(ar1)
ar1.sort(1) #행 단위로 원소를 정렬
print(ar2)

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
[[-7 -6  9]
 [ 5  7 11]
 [ 6  9 19]]
[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]


In [31]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B)) #inner-product
print(np.multiply(A, B)) #element-wise

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [ ]:
def apply_operation(operation, x, y):
    return operation(x, y)

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

result = apply_operation(np.add, A, B)
result = apply_operation(np.subtract, A, B)