In [1]:
import numpy as np

ar5 = np.zeros(5)
ar6 = np.ones((2,3))
print(ar5)
print(ar6)

#new commit
print('this is the new commit')

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
this is the new commit
